### ISSUE TITLE
Create a new workspace called products

### ISSUE THREAD

**Issue by soccerjustinh1** [ngageoint/scale#595]
Version info:

- Scale on master (27th October 2016)
- Vagrant 1.8.7.dev
- ansible 2.3.0

I am trying to deploy the example _landsat_ recipe within the ansible _init-examples_.

However it is expecting a workspace called "products" to already exist!

How can I create a workspace in _Scale_? Can I do this via a **POST** request to the api/v3/workspaces/? Can someone point me at an example of this.

Currently it seems that I have no workspaces as when I send the following **GET** request I get a count of zero.

```
GET request to http://scale-master/api/v3/workspaces/

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}

GET request to http://scale-master/api/v3/version/

{
    "version": "3.1.0"
}
```

**Comment by soccerjustinh1** [comment]
To create a new workspace you can use the existing ansible yml file at:
`ansible/roles/init-examples/tasks/main.yml`

Below the comment is on line 2 of this yml file:
`# configure workspaces`

Add the logic:
```
# Use template to create the products workspace.
- name: Configure products workspace from template
  tags: init-examples
  template: src=products_ws.yml.j2 dest='/tmp/products_ws.yml'

- name: Create the products workspace
  tags: [ init-examples, example-database ]
  command: /scale/bin/goscale ws create -d /tmp/products_ws.yml
  become: true
  environment:
    DOCKER_REGISTRY: "{{ example_docker_registry | replace('/', '') }}"
    SCALE_URL: 'http://{{ mesos_master_ip }}/api/v3'
```

Then send a GET request to your workspaces RESTful end-point:

```
GET request to http://scale-master/api/v3/workspaces/

{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 2,
            "name": "products",
            "title": "products",
            "description": "Product storage",
            "base_url": "http://10.4.4.10:8080/products",
            "is_active": true,
            "used_size": null,
            "total_size": null,
            "created": "2016-11-09T06:14:28.764007Z",
            "archived": null,
            "last_modified": "2016-11-09T06:14:28.764044Z"
        }
    ]
}
```

Hope someone else finds this useful.
